#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

cd $(dirname $0)

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

mkdir -p ~/.lein
cp profiles.clj ~/.lein

sudo cp hub /usr/local/bin

chmod +x /home/syme/.symerc/setup
/home/syme/.symerc/setup &
