#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

cd $(dirname $0)

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

sudo cp hub /usr/local/bin

chmod +x setup
setup &
