#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

SYMERC_DIR=$(dirname $0)
cd $SYMERC_DIR

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

sudo cp hub /usr/local/bin

chmod +x setup
sudo --background --non-interactive $SYMERC_DIR/setup
