#!/bin/bash

sudo apt-get install -y emacs24-nox curl tree unzip zip mosh openjdk-7-jre-headless

sudo wget -qO /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein
sudo chmod +x /usr/local/bin/lein
